- name: Deploy Maven Artifact
  hosts: web
  gather_facts: no
  become: yes
  tasks:
    - name: Copy JAR file
      copy:
        src: maven-example/target/maven-example-1.0-SNAPSHOT.jar
        dest: /opt/maven-example-1.0-SNAPSHOT.jar

    - name: Run application
      shell: nohup java -jar /opt/maven-example-1.0-SNAPSHOT.jar &
