- name: Deploy Maven Artifact
  hosts: web
  gather_facts: no
  tasks:
    - name: Ensure app directory exists 
      file:
        path:/var/lib/jenkins/workspace/maven deploy
        state: directory
        owner: jenkins
        group: jenkins
        mode:'0755'
    - name: Copy JAR file
    copy:
      src: /var/lib/jenkins/workspace/maven deploy/maven-example/target/maven-example-1.0-SNAPSHOT.jar
      dest: /var/lib/jenkins/workspace/maven deploy/maven-example/target/maven-example-1.0-SNAPSHOT.jar

    - name: Run application
      shell: nohup java -jar /var/lib/jenkins/workspace/maven deploy/maven-example/target/maven-example-1.0-SNAPSHOT.jar &
      args:
        chdir:/var/lib/jenkins/workspace/maven deploy/maven-example/target
